### ISSUE TITLE
Integration tests: add note about running tests in a separate OpenShift project

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launch/appdev-documentation#768]
This note is relevant for tests that use OpenShift Test Assistant, which does not automatically create an ephemeral OpenShift project to run the tests in.
This should no longer be an issue after migrating to ARQ Cube.

**Comment by Ladicek** [comment]
Just to clarify: Arquillian Cube allows running tests in an ephemeral namespace/project, and it actually defaults to doing that, but in boosters tests, we configure Arquillian Cube to use the _current_ namespace, similarly to OpenShiftTestAssistant. The reason is that creating a new namespace requires permissions and quotas that you often don't have -- e.g. on OpenShift Online. We want to have the most seamless experience. So this is _also_ relevant to boosters that use Arquillian Cube for tests -- though with Arq Cube, it's enough to add two cmdline parameters to enable running the tests in an ephemeral namespace, unlike OSTA where you have to do it manually.

**Comment by inoxx03** [comment]
This issue duplicates #813

Closing.
