### ISSUE TITLE
The "Breakdown of POM components" Appendix is problematic and/or unnecessary

### ISSUE THREAD

**Issue by tradej** [fabric8-launch/appdev-documentation#824]
The chapter's utility was brought into question; problems:

* The information is too basic.
* It can easily become outdated.
* The components are hardcoded to the community ones.
* Components vary by booster.

Suggestions:

* Remove the chapter altogether.
* Break down the chapter into pieces by booster and include that information in the booster chapter.

**Comment by Ladicek** [comment]
I actually think it is pretty useful. IIRC, it was me who suggested just documenting the POM of the simplest booster :-) While it's true other boosters' POMs contain more configuration, the simplest booster is a building block. And it's the best thing we currently have for users that wish to deconstruct a booster in order to start from scratch. I'd hate losing it, frankly.

CC @metacosm who, I believe, questioned the utility of this.

**Comment by tradej** [comment]
It was not @metacosm, it was a general consensus in the WFS review meeting.

If we decide to keep it, I would advocate for more clarification about the aim and target audience of this chapter.

**Comment by metacosm** [comment]
I indeed questioned its utility because when I saw it, in the context of the Spring Boot runtime, the file was outdated and it wasn't explained at all: it just was picking one pom from one mission without providing context at all and/or explaining how this particular pom might be use in other boosters' poms. So, unless a lot more information is added and the file is kept up to date, I think this provides more out of the blue confusion than usefulness.

**Comment by Ladicek** [comment]
Ah interesting! I was refering to #761. So we have quite a lot of people questioning the usefulness of this.

**Comment by tradej** [comment]
True, but the WFS team liked having some of this information, so if we broke it down into interesting pieces, as opposed to having a single block of XML, it might be worthwhile.

**Comment by lavernw1** [comment]
Yes. Thinking too we were including consistent types of information for each of the runtimes in the appendix section.

**Comment by tradej** [comment]
Closing as the refactoring will be tracked in #858.
