### ISSUE TITLE
WildFly Swarm guide: missing product version number

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launch/appdev-documentation#912]
The Swarm guide doesn't tell what's the version number to use when adding Maven dependencies. What's more, when showing the BOM usage, it even uses a community version number for demonstration!

FTR, the correct version number for our first GA is `7.0.0.redhat-8`.

**Comment by inoxx03** [comment]
@tradej FYI^^

**Comment by inoxx03** [comment]
resolved in #917

**Comment by inoxx03** [comment]
@Ladicek Thank you for catching this. I've updated the version attribute to show the productized version instead of the community one. 
I think for adding dependencies the guide makes it quite clear that you can specify the dependency version as a property and then reference that property to specify the version of each dependency (The way, I believe, it is also done in the BOM file). Still, we can have the version displayed explicitly in the examples if that would be  preferable.
