### ISSUE TITLE
Release Notes: check support of vert.x

### ISSUE THREAD

**Issue by ccopelloRH** [fabric8-launch/appdev-documentation#943]
Per chapter 2 and also 6.1, Vert.x is unsupported. Is that really the case?

**Comment by inoxx03** [comment]
@Ladicek Indeed id turns out That some Vert.x artifacts are supported thank you for catching this
I have confirmed with Rodney that the only Vert.X components that have the `3.4.2.redhat-006` version in the BOM are supported. I have updated the list release notes and marked the component list as _Supported_ for supported components. The Vertx tech preview artifact list seems to be correct.

Updated RN here: https://access.qa.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html-single/red_hat_openshift_application_runtimes_release_notes/

**Comment by Ladicek** [comment]
Thanks @inoxx03, LGTM now.

**Comment by Ladicek** [comment]
This has been fixed.
